baseURL = "https://shrikrishna10.github.io/"
languageCode = "en-us"
title = "Shrikrishna Pandit"
theme = "hugo-xmin"

[params]
  name = "Shrikrishna Pandit"
  avatar = "images/profile.jpg"
#  bio = """ECE @ PES University
#Focus: VLSI, FPGA Design, Verification
#Open to Research Roles"""
  github = "https://github.com/Shrikrishna10"
  linkedin = "https://linkedin.com/in/shrikrishna-pandit"

[menu]

  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Blog"
  url = "/post/"
  weight = 2

  [[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3

  [[menu.main]]
  name = "Resume"
  url = "/resume/"
  weight = 4

  [[menu.main]]
  name = "GitHub"
  url = "https://github.com/Shrikrishna10"
  weight = 5

  [[menu.main]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/shrikrishna-pandit-250b5424b/"
  weight = 6

